spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: usr
    password: pwd

logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: TRACE
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG