spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:library}
    username: ${POSTGRES_USER:usr}
    password: ${POSTGRES_PASSWORD:pwd}

logging:
  level:
    org:
      springframework:
        transaction:
          interceptor: TRACE
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG